name: Main Branch CI Pipeline

on: push

jobs:
  main:
    name: Tag Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Find Latest Tag
        run: |
          echo "$(git describe --tags --abbrev=0)"
          echo "latest_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Bump Release Version
        id: bump_version
        uses: FrelliSandbox/increment-semantic-version@1.0.2
        with:
          current-version: ${{ env.latest_tag }}
          version-fragment: 'feature'

      - name: Print Things
        run: |
          echo "env.latest_tag=${{ env.latest_tag }}"
          echo "steps.bump_version.outputs.next-version=${{ steps.bump_version.outputs.next-version }}"


