name: Versioning

on: pull_request

jobs:
  version:
    name: Determine Version
    runs-on: ubuntu-latest
    steps:
      - name: Set project_version
        run: |
          echo "project_version=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
      - name: Use project_version
        run: |
          echo "${{ env.project_version }}"
